=== juanger/scielo-dev/PDF2Scielo/PDF2Text/Data/style.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.scielo.org.mx"
xmlns="http://www.scielo.org.mx"
elementFormDefault="qualified">

<xs:complexType name="paramtype">
  <xs:attribute name="name" type="nametype" use="required" />
  <xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="modifiertype">
  <xs:all>
    <xs:element name="param" type="paramtype" minOccurs="0" maxOccurs="unbounded"/>
  </xs:all>
  <xs:attribute name="name" type="nametype" use="required" />
  <xs:attribute name="target" type="nametype"/>
  <xs:attribute name="return" type="nametype"/>
</xs:complexType>

<xs:complexType name="modifierstype">
  <xs:all>
    <xs:element name="modifier" type="modifiertype" minOccures="0" maxOccurs="unbounded"/>
  </xs:all>
</xs:complexType>

<xs:complexType name="dependstype">
  <xs:all>
    <xs:element name="depend" type="nametype" minOccures="0" maxOccurs="unbounded"/>
  </xs:all>
</xs:complexType>

<xs:simpleType name="limittype">
  <xs:restriction base="xs:string">
    <xs:enumeration value="one"/>
    <xs:enumeration value="unbounded"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="ruletype">
  <xs:sequence>
    <xs:element name="depends" type="dependstype" minOccurs="0"/>
    <xs:element name="regexp" type="xs:string"/>
    <xs:element name="sust" type="xs:string"/>
    <xs:element name="modifiers" type="modifierstype" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required" />
  <xs:attribute name="limit" type="limittype" default="one" />
</xs:complexType>

<xs:complexType name="globaltype">
  <xs:all>
    <xs:element name="rule" type="ruletype" maxOccurs="unbounded"/>
  </xs:all>
</xs:complexType>

<xs:complexType name="blocktype">
  <xs:all>
    <xs:element name="rule" type="ruletype" minOccurs="0" maxOccurs="unbounded"/>
  </xs:all>
</xs:complexType>

<xs:simpleType name="nametype">
  <xs:restriction base="xs:string">
    <xs:pattern value="([a-zA-Z])+"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="columntype">
  <xs:restriction base="xs:positiveInteger" >
    <xs:pattern value="[0-3]" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="styletype">
  <xs:sequence>
    <xs:element name="global" type="globaltype" />
    <xs:element name="front" type="blocktype" />
    <xs:element name="body" type="blocktype" />
    <xs:element name="back" type="blocktype" />
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required" />
  <xs:attribute name="ncolumns" type="columntype" default="1" />
</xs:complexType>

<xs:element name="style" type="styletype" />

</xs:schema>

=== juanger/scielo-dev/PDF2Scielo/PDF2Text/Test/test-schema.xml
<?xml version="1.0"?>
<style xmlns="http://www.scielo.org.mx"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.scielo.org.mx style.xsd" name="atm" ncolumns="1">
  <global>
    <rule name="RemoveHeaders">
      <regexp>[\n]+[\u000c]+[0-9]+[ ]*[-a-zA-Z. \u00f1\u002f\u0050-\u00ff’,()&amp;;]+[\n]+</regexp>
      <sust>\n</sust>
    </rule>
    <rule name="DeadText">
      <depends>
      	<depend>RemoveHeaders</depend>
      </depends>
      <regexp>[\n]+[\u000c]+[ ]*[-a-zA-Z0-9. \u00f1\u002f\u0050-\u00ff#’,()&amp;;]+</regexp>
      <sust>\n</sust>
    </rule>
    <rule name="MarkResumen">
      <regexp>[\n]+[ ]+RESUMEN[\n]+</regexp>
      <sust>\n[res] Resumen [/res]\n</sust>
    </rule>
    <rule name="MarkAbstract">
      <regexp>[\n]+[ ]+ABSTRACT[\n]+</regexp>
      <sust>\n[abs] Abstract [/abs]\n</sust>
    </rule>
    <rule name="MarkReferences">
      <regexp>[\n]+References\n</regexp>
      <sust>\n[ref] References [/ref]\n</sust>
    </rule>
    <rule name="MarkAcknowledge">
      <regexp>[\n]+[ ]*(Acknowledgement|Acknowledgment)[s]?\n</regexp>
      <sust>\n[ack] Acknowledgements [/ack]\n</sust>
    </rule>
    <rule name="MarkKeyword">
      <regexp>[\n]+(Key words|Keywords|Keyword|Key word):[ ]+[a-zA-Z,;.&amp;\u002d \n]+[\n]+</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[key] "/>
          <param name="postfix" value=" [/key]\n\n"/>
        </modifier>
      </modifiers>
    </rule>
  </global>
  <front>
    <rule name="MarkTitle">
      <regexp>^Atm.*[\n]+[^|]+?\n[\n]+</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="IndexOf" return="#{index}">
          <param name="string" value="\n"/>
        </modifier>
        <modifier name="Substring">
         <param name="index" value="#{index}"/>
        </modifier>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="[title] "/>
          <param name="postfix" value=" [/title]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkDate">
      <regexp>\n[ ]+Received.*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[date] "/>
          <param name="postfix" value=" [/date]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkAuthors">
      <regexp>[ ]*(([A-Z]{1,2}\. ([A-Z]{1,2}[.]? )*[-A-Z][-a-zA-Z&amp;;]+( [-a-zA-Z&amp;;]+)?)(, | and )?)+[\n]+</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="[author] "/>
          <param name="postfix" value=" [/author]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarAff">
      <depends>
      	<depend>MarkAuthors</depend>
      	<depend>MarkDate</depend>
      </depends>
      <regexp>\[/author\]\n(.|\n)+?(\[author\]|\[date\]|\[res\])</regexp>
      <sust>#{result}</sust>
      <modifiers>
      	<modifier name="IndexOf" return="#{index}">
      	  <param name="string" value="\n"/>
      	</modifier>
      	<modifier name="Substring" return="#{result}" >
      	  <param name="index" value="#{index}"/>
      	</modifier>
      	<modifier name="LastIndexOf" return="#{index}" target="#{result}">
      	  <param name="string" value="["/>
      	</modifier>
      	<modifier name="Substring" return="#{tag}" target="#{result}">
      	  <param name="index" value="#{index}"/>
      	</modifier>
        <modifier name="Substring" target="#{result}" >
      	  <param name="sindex" value="0"/>
      	  <param name="lindex" value="#{index}" />
      	</modifier>
      	<modifier name="Trim"/>
        <modifier name="Concat">
          <param name="prefix" value="[/author]\n[aff] "/>
          <param name="postfix" value=" [/aff]\n"/>
        </modifier>
        <modifier name="Concat">
          <param name="postfix" value="#{tag}"/>
        </modifier>
      </modifiers>
    </rule>
  </front>
  <body>
    <rule name="RemoveExtras">
      <regexp>\n[ ]*[-0-9.]+\n</regexp>
      <sust>\n</sust>
    </rule>
    <rule name="MarkSections">
      <regexp>[\n]+[0-9]+[.][ ].*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[sec] "/>
          <param name="postfix" value=" [/sec]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkSubSections">
      <regexp>[\n]+[ ]*[0-9][.][0-9]+[.]*[ ].*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[subsec] "/>
          <param name="postfix" value=" [/subsec]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkAlternSubSections">
      <regexp>[\n]+[a-z]\) .*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[subsec] "/>
          <param name="postfix" value=" [/subsec]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkSubSubSections">
      <regexp>[\n]+[0-9][.][0-9]+[.][0-9][.]*.*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Trim" />
        <modifier name="Concat">
          <param name="prefix" value="\n[subsubsec] "/>
          <param name="postfix" value=" [/subsubsec]\n"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkStartParagraphs0">
      <regexp>[\n]+[ ]{3,5}[A-Zi].*</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="TrimStart" />
        <modifier name="Concat">
          <param name="prefix" value="\n[para] "/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkStartParagraphs1">
      <depends>
      	<depend>MarkSections</depend>
      	<depend>MarkaAlternSubsections</depend>
      	<depend>MarkSubSections</depend>
      	<depend>MarkSubSubSections</depend>
      </depends>
      <regexp>(\[sec\]|\[subsec\]|\[subsubsec\]).*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="TrimStart" />
        <modifier name="Concat">
          <param name="prefix" value=" [/para]"/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkEndParagraphs">
      <depends>
      	<depend>MarkStartParagraphs0</depend>
      	<depend>MarkStartParagraphs1</depend>
      	<depend>MarkSections</depend>
      	<depend>MarkAlternSubSections</depend>
      	<depend>MarkSubSections</depend>
      	<depend>MarkSubSubSections</depend>
      	<depend>MarkAciknowledge</depend>
      </depends>
      <regexp>(\[sec\]|\[subsec\]|\[subsubsec\]).*\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Concat">
          <param name="prefix" value="[para] "/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkStartFootFigure">
      <regexp>[\n]+[ ]*Fig[.][ ]?[0-9]+[.] .*</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="TrimStart" />
        <modifier name="Concat">
          <param name="prefix" value="\n[fig] "/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkEndFootFigure">
    <depends>
      <depend>MarkStartFootFigure</depend>
    </depends>
      <regexp>\[fig\] Fig[.][ ]?[0-9]+[.] [-a-zA-Z0-9.,:;´&amp;#()/ \n\u00f6]*?[.]\n</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="TrimEnd" />
        <modifier name="Concat">
          <param name="postfix" value=" [/fig]\n"/>
        </modifier>
      </modifiers>
    </rule>
  </body>
  <back>
    <rule name="MarkStartCitations">
      <regexp>[\n]+[A-Z].*</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="Concat">
          <param name="prefix" value="[cit] "/>
        </modifier>
      </modifiers>
    </rule>
    <rule name="MarkEndCitations">
      <regexp>[\n]+[A-Z].*</regexp>
      <sust>#{result}</sust>
      <modifiers>
        <modifier name="TrimEnd" />
        <modifier name="Concat">
          <param name="postfix" value=" [/cit]\n"/>
        </modifier>
      </modifiers>
    </rule>
  </back>
</style>
