=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/dfa.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT sym (#PCDATA)>

<!ELEMENT alph (sym)*>

<!ELEMENT str (epsilon|(sym)+)>

<!ELEMENT epsilon EMPTY>

<!ELEMENT state (#PCDATA)>
<!ATTLIST state xpos CDATA #IMPLIED>
<!ATTLIST state ypos CDATA #IMPLIED>

<!ELEMENT stateSet (state)*>

<!-- Para DFA -->
<!ELEMENT description (#PCDATA)>

<!ELEMENT trans (state, sym, state)>

<!ELEMENT delta (trans)*>

<!ELEMENT dfa (description?, stateSet, alph, delta, state, stateSet)>

=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/dfa-002.xml
<?xml version='1.0' encoding="iso-8859-1" ?>

<!DOCTYPE dfa SYSTEM "dfa.dtd">

<!-- Un DFA  M es un quntuplo (Q,Sigma,delta,q0,F) -->

<dfa>
    <description>Este automata acepta cadenas que tengan como subcadena 001</description>

   <stateSet>
	<state>q</state>
	<state>q0</state>
	<state>q00</state>
	<state>q001</state>
   </stateSet>

   <alph>
	<sym>0</sym>
	<sym>1</sym>
   </alph>

   <delta>
	<trans> <state>q</state> <sym>0</sym> <state>q0</state> </trans>
	<trans> <state>q</state> <sym>1</sym> <state>q</state> </trans>
	<trans> <state>q0</state> <sym>0</sym> <state>q00</state> </trans>
	<trans> <state>q0</state> <sym>1</sym> <state>q</state> </trans>
	<trans> <state>q00</state> <sym>0</sym> <state>q00</state> </trans>
	<trans> <state>q00</state> <sym>1</sym> <state>q001</state> </trans>
	<trans> <state>q001</state> <sym>0</sym> <state>q001</state> </trans>
	<trans> <state>q001</state> <sym>1</sym> <state>q001</state> </trans>
   </delta>

   <state>q</state>

   <stateSet>
   	   <state>q</state>
	   <state>q001</state>
   </stateSet>

</dfa>

=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/dfa-cero-star-uno-cero-plus.xml
<?xml version='1.0' encoding="iso-8859-1" ?>
<!DOCTYPE dfa SYSTEM "dfa.dtd">

<!-- Un DFA  M es un quíntuplo (Q,Sigma,delta,q0,F) -->

<dfa>

  <description> Este autómata reconoce el lenguaje 0^{*}10^{+}</description>

  <stateSet>
	<state>A</state>
	<state>B</state>
	<state>C</state>
  </stateSet>

   <alph>
	<sym>0</sym>
	<sym>1</sym>
   </alph>

   <delta>
	<trans> <state>A</state> <sym>0</sym> <state>A</state> </trans>
	<trans> <state>A</state> <sym>1</sym> <state>B</state> </trans>
	<trans> <state>B</state> <sym>0</sym> <state>C</state> </trans>
	<trans> <state>C</state> <sym>0</sym> <state>C</state> </trans>
   </delta>

   <state>A</state>

   <stateSet>
	   <state>C</state>
   </stateSet>

</dfa>
