=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/ndfa.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT sym (#PCDATA)>

<!ELEMENT alph (sym)*>

<!ELEMENT str (epsilon|(sym)+)>

<!ELEMENT epsilon EMPTY>

<!ELEMENT state (#PCDATA)>
<!ATTLIST state final (true|false) #IMPLIED
                xpos CDATA #IMPLIED
                ypos CDATA #IMPLIED>

<!ELEMENT stateSet (state)*>

<!-- Aquí comienza, propiamente la definición de un NDFA --> 
<!ELEMENT description (#PCDATA)>

<!ELEMENT trans (state, sym, stateSet)>

<!ELEMENT delta (trans)*>

<!ELEMENT ndfa (description?, stateSet, alph, delta, stateSet, stateSet)>

=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/ndfa-ab-star-union-a.xml
<?xml version='1.0' encoding="iso-8859-1" ?>

<!DOCTYPE ndfa SYSTEM "ndfa.dtd">

<ndfa> 

<description> Acepta el lenguaje L = L1 U L2, donde: L1 = (ab)*, L2 = {a}</description>

<stateSet> <state>q0</state> <state>q1</state> <state>q2</state> <state>q3</state> <state>q4</state> </stateSet> 

<alph> <sym>a</sym> <sym>b</sym> </alph> 

<delta> 
	<trans> <state>q0</state> <sym>a</sym> <stateSet> <state>q1</state> <state>q3</state> </stateSet> </trans> 
	<trans> <state>q0</state> <sym>b</sym> <stateSet> <state>q4</state> </stateSet> </trans> 
	<trans> <state>q1</state> <sym>b</sym> <stateSet> <state>q2</state> </stateSet> </trans> 
	<trans> <state>q2</state> <sym>a</sym> <stateSet> <state>q1</state> </stateSet> </trans> 
	<trans> <state>q2</state> <sym>b</sym> <stateSet> <state>q4</state> </stateSet> </trans> 
	<trans> <state>q3</state> <sym>a</sym> <stateSet> <state>q4</state> </stateSet> </trans> 
	<trans> <state>q3</state> <sym>b</sym> <stateSet> <state>q4</state> </stateSet> </trans> 
	<trans> <state>q4</state> <sym>a</sym> <stateSet> <state>q4</state> </stateSet> </trans> 
	<trans> <state>q4</state> <sym>b</sym> <stateSet> <state>q4</state> </stateSet> </trans>
</delta>

<stateSet> <state>q0</state> </stateSet> 
<stateSet> <state>q0</state> <state>q2</state> <state>q3</state> </stateSet> 

</ndfa>

=== juanger/scielo-dev/AutomataFinito/AutomataLibrary/Data/ndfa-foo.xml
<?xml version='1.0' encoding="iso-8859-1" ?>

<!DOCTYPE ndfa SYSTEM "ndfa.dtd">

<!-- Un NDFA  M es un quíntuplo (Q,Sigma,delta,q0,F) -->

<ndfa>
    <description>Este autómata acepta (01^{+})^{+}</description>

  <!--    Conjunto de estados Q -->
   <stateSet>
	<state>A</state>
	<state>B</state>
	<state>C</state>
   </stateSet>

  <!--    Alfabeto de entrada Sigma -->
   <alph>
	<sym>0</sym>
	<sym>1</sym>
   </alph>

  <!--    Función de transición delta -->
   <delta>
	<trans> <state>A</state> <sym>0</sym>   <stateSet><state>B</state>  </stateSet>  </trans>
	<trans> <state>B</state> <sym>1</sym>   <stateSet><state>B</state> <state>C</state> <state>A</state> </stateSet>  </trans>
   </delta>

  <!--    Estado inicial q0 -->
   <stateSet> <state>A</state>    </stateSet>

  <!--    Conjunto de estados finales F -->
   <stateSet>
	   <state>C</state>
   </stateSet>

</ndfa>
